### ISSUE TITLE
Cannot read property 'room' of undefined

### ISSUE THREAD

**Issue by eungjun-yi** [renanvicente/hubot-mattermost#11]
It occurs when I install and try to use [hubot-github-repo-event-notifier](https://github.com/hubot-scripts/hubot-github-repo-event-notifier).

```
TypeError: Cannot read property 'room' of undefined
  at Mattermost.send (/home/hubot/node_modules/hubot-mattermost/src/mattermost.coffee:13:9, <js>:30:74)
  at Robot.messageRoom (/home/hubot/node_modules/hubot/src/robot.coffee:560:19, <js>:444:42)
  at /home/hubot/node_modules/hubot-github-repo-event-notifier/src/github-repo-event-notifier.coffee:100:7, <js>:74:15
  at callbacks (/home/hubot/node_modules/express/lib/router/index.js:164:37)
  at param (/home/hubot/node_modules/express/lib/router/index.js:138:11)
  at pass (/home/hubot/node_modules/express/lib/router/index.js:145:5)
  at Router._dispatch (/home/hubot/node_modules/express/lib/router/index.js:173:5)
  at Object.router (/home/hubot/node_modules/express/lib/router/index.js:33:10)
  at next (/home/hubot/node_modules/connect/lib/proto.js:169:15)
  at Object.multipart [as handle] (/home/hubot/node_modules/connect-multiparty/index.js:42:27)
  at next (/home/hubot/node_modules/connect/lib/proto.js:169:15)
  at Object.urlencodedParser [as handle] (/home/hubot/node_modules/body-parser/lib/types/urlencoded.js:69:27)
  at next (/home/hubot/node_modules/connect/lib/proto.js:169:15)
  at /home/hubot/node_modules/body-parser/lib/read.js:107:5
  at IncomingMessage.onEnd (/home/hubot/node_modules/raw-body/index.js:136:7)
  at IncomingMessage.g (events.js:199:16)
  at IncomingMessage.emit (events.js:104:17)
  at _stream_readable.js:908:16
  at process._tickCallback (node.js:355:11)
```

**Comment by eungjun-yi** [comment]
It seems that Mattermost.send accepts 'envelope' as the first argument.

``` coffee
class Mattermost extends Adapter

  send: (envelope, strings...) ->
    for str in strings
      data = JSON.stringify({
        icon_url: @icon,
        channel: @channel ? envelope.user.room, # send back to source channel only if not overwritten,
        username: @username,
        text: str
      })
      @robot.http(@url)
        .header('Content-Type', 'application/json')
        .post(data) (err, res, body) ->
          if err
            console.log err
```

But robot.coffee sends 'user' as the first argument.

``` coffee
  messageRoom: (room, strings...) ->
    user = { room: room }
    @adapter.send user, strings...
```

**Comment by inty** [comment]
I ran into this issue with hubot-standup-alarm too

**Comment by heitorlessa** [comment]
Hi,

There's a PR Request already opened that should fix this.

As soon as I come back from travelling I will give a last test, approve PR
and let you know if that in fact also fixes this issue here.

Thanks for reporting that, much appreciated.

**Comment by heitorlessa** [comment]
@npcode @inty 

just pushed 1.0.7 to both NPM and Github, that should fix this issue. 

Could you please give it a spin?

[Credits](https://github.com/renanvicente/hubot-mattermost/commit/12d96f486274bf80dca92e4add5e90e397a0b076) to @jbick

**Comment by eungjun-yi** [comment]
@heitorlessa It works well. Thanks!

**Comment by heitorlessa** [comment]
great! Tks for letting me know @npcode
